name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

#      - name: Build and deploy
#        uses: helaili/jekyll-action@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          target_branch: 'gh-pages'
#         # target_path: '_site'

      - name: Bundle config
      - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build and deploy
      - run: bundle exec jekyll build

      - name: C
        run: ls -la

       - name: Cache HTMLProofer
         id: cache-htmlproofer
         uses: actions/cache@v2
         with:
           path: tmp/.htmlproofer
           key: ${{ runner.os }}-htmlproofer

      - name: Check HTML
        uses: anishathalye/proof-html@v1
        with:
          directory: "./_site"
          check_favicon: true
          check_html: true
          check_opengraph: false
